config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'

  resources :user_groups

  resources :posts do
    resources :user_groups, only: %i[index]
  end

  resources :users, except: %i[show] do
    resources :user_groups, only: %i[index]
  end

  get :profile, to: 'users#edit'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, Post do |post|
        Post.readable(user).include?(post)
      end

      can :update, User, id: user.id
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < User
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_user_groups
  has_many :user_groups, through: :post_user_groups

  has_many :users, through: :user_groups

  after_create :send_notifications

  DEFAULT_PICTURE_URL = '/images/:style/missing.png'.freeze

  is_impressionable

  has_attached_file :picture, styles: { medium: '300x300>', thumb: '150x150>' },
                              default_url: DEFAULT_PICTURE_URL

  has_attached_file :attached_file

  validates_attachment :picture, size: { in: 0..5.megabytes }
  validates_attachment_content_type :picture, content_type: %r{\Aimage\/.*\z}

  validates :title, presence: true

  scope :readable, ->(user) { user.admin? ? Post.all : Post.not_admin_readable(user) }

  def targets
    user_groups.size.zero? ? User.all : users.distinct
  end

  class << self
    def not_admin_readable(user)
      includes(:user_groups).where(user_groups: { id: [nil, *user.user_groups] })
    end
  end

  private

  def send_notifications
    Posts::NewPostNotification.call(post: self)
  end
end

app/models/post_user_group.rb
class PostUserGroup < ApplicationRecord
  belongs_to :post,       inverse_of: :user_groups
  belongs_to :user_group, inverse_of: :posts
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_many :user_group_users
  has_many :user_groups, through: :user_group_users

  validates :first_name, :last_name, presence: true

  def admin?
    is_a? Admin
  end

  def employee?
    is_a? Employee
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :user_group_users
  has_many :users, through: :user_group_users

  has_many :post_user_groups
  has_many :posts, through: :post_user_groups

  validates :group_name, presence: true
end

app/models/user_group_user.rb
class UserGroupUser < ApplicationRecord
  belongs_to :user,       inverse_of: :user_groups
  belongs_to :user_group, inverse_of: :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to root_path, notice: exception.message }
    end
  end

  rescue_from ActiveRecord::RecordNotFound do
    render file: 'public/404.html', status: 404
  end

  def pagination_params
    {
      page:     params[:page],
      per_page: 5
    }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,        only: %i[show edit update destroy]
  before_action :prepare_params,  only: %i[create update]

  decorates_assigned :post

  load_and_authorize_resource

  impressionist actions: %i[show], unique: %i[user_id impressionable_id]

  def index
    @facade = Posts::IndexFacade.new(
      query:             params[:q],
      pagination_params: pagination_params,
      current_user:      current_user
    )
  end

  def show
    @facade = Posts::CoverageSummary.new(post: post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Posts::Create.call(params: post_params)

    render :new and return unless @post.persisted?

    redirect_to @post, notice: t('notices.created', item: Post.name)
  end

  def update
    render :edit unless @post.update(post_params)

    redirect_to @post, notice: t('notices.updated', item: Post.name)
  end

  def destroy
    Shared::Destroy.call(item: @post)

    redirect_to posts_url, notice: t('notices.destroyed', item: Post.name)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :title,
      :content,
      :picture,
      :attached_file,
      user_group_ids: []
    )
  end

  def prepare_params
    params[:post][:user_group_ids] ||= []
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group,        only: %i[show edit update destroy]
  before_action :create_new_user_group, only: %i[index]

  decorates_assigned :user_group
  decorates_assigned :users

  load_and_authorize_resource

  def index
    @facade = UserGroups::IndexFacade.new(
      params:            params,
      pagination_params: pagination_params
    )
  end

  def create
    @user_group = UserGroups::Create.call(params: user_group_params)

    render :new and return unless @user_group.persisted?

    redirect_to user_groups_url, notice: t('notices.created', item: UserGroup.name)
  end

  def update
    render :edit unless @user_group.update(user_group_params)

    redirect_to user_groups_path, notice: t('notices.updated', item: UserGroup.name)
  end

  def destroy
    Shared::Destroy.call(item: @user_group)

    redirect_to user_groups_url, notice: t('notices.destroyed', item: UserGroup.name)
  end

  private

  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end

  def create_new_user_group
    @user_group = UserGroup.new
  end

  def user_group_params
    params.require(:user_group).permit(
      :group_name,
      post_ids: [],
      user_ids: []
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,        only: %i[update destroy]
  before_action :create_new_user, only: %i[index new]
  before_action :prepare_params,  only: %i[create update]

  load_and_authorize_resource

  def index
    @facade = Users::IndexFacade.new(
      query:             params[:q],
      pagination_params: pagination_params
    )
  end

  def edit
    @user = Users::Edit.call(user_id: params[:id], current_user: current_user)
  end

  def create
    @user = Users::Create.call(params: user_params)

    render :new and return unless @user.persisted?

    redirect_to users_path, notice: t('notices.created', item: User.name)
  end

  def update
    render :edit and return unless @user.update(user_params)

    redirect_back fallback_location: root_path, notice: t('notices.updated', item: User.name)
  end

  def destroy
    Shared::Destroy.call(item: @user)

    redirect_to users_path, notice: t('notices.destroyed', item: User.name)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def create_new_user
    @user = User.new
  end

  def user_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation,
      user_group_ids: []
    )
  end

  def prepare_params
    params[:user][:user_group_ids] ||= []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_attribute(attribute)
    attribute.to_s.humanize
  end

  def form_group(attribute, form, field_type, required = false)
    content = [
      form.label(attribute),
      form.send(field_type, attribute, class: 'form-control', required: required)
    ].join("\n")

    content_tag(:div, class: 'form-group') { content.html_safe }
  end

  def flash_class(level)
    case level.to_sym
    when :notice  then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error   then 'alert alert-error'
    when :alert   then 'alert alert-error'
    end
  end

  def active_class(link_path)
    'active' if current_page?(link_path)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HRDepartment
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'shared/navbar'
    .container-fluid
      = render 'shared/notices'
      = yield

app/views/posts/_admin_dashboard.html.haml
.well
  %h4
    %span= t('posts.dashboard.percentage')
    %span= facade.percentage if facade.targets?
    %span (#{t('posts.dashboard.out_of', current: facade.views, target: facade.targets.size)})

app/views/posts/_form.html.haml
= form_for post do |f|
  = render 'shared/form_errors', item: post

  = form_group(:title,         f, :text_field, true)
  = form_group(:content,       f, :text_area, true)
  = form_group(:picture,       f, :file_field)
  = form_group(:attached_file, f, :file_field)

  = f.label :user_groups
  = f.select :user_group_ids, [], {}, class: 'select-group', style: 'width: 100%', name: 'post[user_group_ids][]'

  %hr

  .actions= f.submit t('defaults.save'), class: 'form-control'

:coffee
  handler = new HRDepartment.Autocomplete(
    '.select-group',
    "#{user_groups_path}",
    'group_name_cont',
    "#{post_user_groups_path(post, format: :json) unless post.new_record?}"
  )
  handler.init()

app/views/posts/_post.html.haml
.well
  .media
    .pull-left
      = image_tag post.picture.url(:thumb)
    .media-body
      %h4.text-left #{post.title} (#{post.created_ago})
      %p= post.content
      - if post.attached_file.present?
        %hr
        = link_to t('posts.download_attachment'), post.attached_file.url(:original)

      %hr
        = render 'tags', item: post

app/views/posts/_tags.html.haml
%span.label.label-success= t('posts.everyone') if item.user_groups.empty?

- item.user_groups.each do |group|
  %span.label.label-success= group.group_name

app/views/posts/edit.html.haml
= render 'form'

app/views/posts/index.html.haml
- if can? :manage, Post
  .well.container.text-center
    = link_to t('defaults.create'), new_post_path, class: 'btn btn-success'

= render 'shared/search_bar', query: @facade.ransack_query, searchable_fields: :title_or_content_cont

- @facade.posts.each do |post|
  .well
    .container
      .row
        .col-sm-3
          = image_tag post.picture.url(:thumb)
        .col-sm-3
          %h3= link_to post.title, post
        .col-sm-3
          = render 'tags', item: post
        - if can? :manage, post
          .col-sm-3
            = link_to t('defaults.destroy'), post_path(post), method: :delete, data: { confirm: t('defaults.confirmation') }, class: 'btn btn-danger pull-right'
            = link_to t('defaults.edit'), edit_post_path(post), class: 'btn btn-primary pull-right'

.text-center
  = will_paginate @facade.posts, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer

app/views/posts/new.html.haml
.well
  = render 'form'

app/views/posts/show.html.haml
.container
  = render 'admin_dashboard', facade: @facade if current_user.admin?
  = render 'post', post: post

app/views/shared/_admin_menu_items.html.haml
%li{ class: active_class(users_path) }
  = link_to t('navbar.users'), users_path
%li{ class: active_class(user_groups_path) }
  = link_to t('navbar.user_groups'), user_groups_path

app/views/shared/_form_errors.html.haml
- if item.errors.any?
  #error_explanation
    %ul
      - item.errors.full_messages.each do |message|
        %li= message

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %a.navbar-brand= I18n.t('defaults.title')
    %ul.nav.navbar-nav
      - if user_signed_in?
        = render 'shared/admin_menu_items' if current_user&.admin?

        %li{ class: active_class(profile_path) }
          = link_to t('navbar.profile'), profile_path

        %li{ class: active_class(posts_path) }
          = link_to t('navbar.posts'), posts_path

        %li.pull-right
          = link_to t('authentication.logout'), destroy_user_session_path, method: :delete

app/views/shared/_notices.html.haml
- flash.each do |key, value|
  %div{ class: flash_class(key) }= value

app/views/shared/_search_bar.html.haml
.container.well
  .row
    .col-sm-6.col-sm-offset-3.stylish-input-group
      = search_form_for query do |f|
        = f.search_field searchable_fields, class: 'form-control', placeholder: t('defaults.search')
        = button_tag(type: 'submit') do
          %span.glyphicon.glyphicon-search

app/views/user_groups/_form.html.haml
= form_for user_group do |f|
  = render 'shared/form_errors', item: user_group

  = form_group(:group_name, f, :text_field, true)

  .actions= f.submit t('defaults.save'), class: 'form-control'

app/views/user_groups/_table.html.haml
%table.table.table-responsive.table-striped
  %thead
    %tr
      %th= humanize_attribute(:group_name)
      %th= humanize_attribute(:users_count)
      %th

  %tbody
    - user_groups.each do |user_group|
      %tr
        %td= user_group.group_name
        %td= user_group.users.size
        %td
          = link_to t('defaults.destroy'), user_group, method: :delete, data: { confirm: t('defaults.confirmation') }, class: 'btn btn-danger pull-right'
          = link_to t('defaults.edit'), edit_user_group_path(user_group), class: 'btn btn-primary pull-right'

.text-center
  = will_paginate user_groups, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer

app/views/user_groups/edit.html.haml
= render 'form', user_group: @user_group

app/views/user_groups/index.html.haml
.container
  %ul.nav.nav-tabs
    %li.active
      %a{ data: { toggle: 'tab' }, href: '#user-groups' }= t('user_groups.title')
    %li
      %a{ data: { toggle: 'tab' }, href: '#create-user-group'}= t('user_groups.create')

  .tab-content
    #user-groups.tab-pane.fade.in.active
      = render 'shared/search_bar', query: @facade.ransack_query, searchable_fields: :group_name_cont
      = render 'table', user_groups: @facade.user_groups

    #create-user-group.tab-pane.fade.well
      = render 'form', user_group: @user_group

app/views/users/_form.html.haml
= form_for user, as: :user, url: user.new_record? ? users_path : user_path(user) do |f|
  = render 'shared/form_errors', item: user

  = form_group(:email,      f, :email_field, true)
  = form_group(:first_name, f, :text_field, true)
  = form_group(:last_name,  f, :text_field, true)

  - if user.new_record?
    = form_group(:password,              f, :password_field)
    = form_group(:password_confirmation, f, :password_field)

  - if current_user.admin?
    = render 'user_groups', user: user, f: f

  .actions= f.submit t('defaults.save'), class: 'form-control'

app/views/users/_table.html.haml
%table.table.table-responsive.table-striped.mt-5
  %thead
    %th= humanize_attribute(:email)
    %th= humanize_attribute(:first_name)
    %th= humanize_attribute(:last_name)
    %th

  %tbody
    - users.each do |user|
      %tr
        %td= user.email
        %td= user.first_name
        %td= user.last_name
        %td
          = link_to t('defaults.destroy'), user_path(user), method: :delete, data: { confirm: t('defaults.confirmation') }, class: 'btn btn-danger pull-right'
          = link_to t('defaults.edit'), edit_user_path(user), class: 'btn btn-primary pull-right'

.text-center
  = will_paginate users, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer

app/views/users/_user_groups.html.haml
= f.label :user_groups

.well
  = f.select :user_group_ids, [], {}, class: 'select-group', style: 'width: 100%', name: 'user[user_group_ids][]'

:coffee
  handler = new HRDepartment.Autocomplete(
    '.select-group',
    "#{user_groups_path}",
    'group_name_cont',
    "#{user_user_groups_path(user, format: :json) unless user.new_record?}"
  )

  handler.init()

app/views/users/edit.html.haml
.container
  = render 'form', user: @user

app/views/users/index.html.haml
.container
  %ul.nav.nav-tabs
    %li.active
      %a{ data: { toggle: 'tab' }, href: '#users' }= t('users.title')
    %li
      %a{ data: { toggle: 'tab' }, href: '#create-user'}= t('users.create')

  .tab-content
    #users.tab-pane.fade.in.active
      = render 'shared/search_bar', query: @facade.ransack_query, searchable_fields: :first_name_or_last_name_or_email_cont
      = render 'table', users: @facade.users
    #create-user.tab-pane.fade.well
      = render 'form', user: @user

app/views/users/new.html.haml
%h2= t('users.create')

= render 'form', user: @user